### ISSUE TITLE
[question]: Mater Detail within tab view

### ISSUE THREAD

**Issue by dgavigan** [NativeScript/template-tab-navigation-ng#24]
is it possible to do a master detail within a tab view (and maintain the tabs while navigating)? 

from my initial test, I believe you need to replace the page router with router outlets for more complex UIs. Once you do this, it removes all animations. I believe support for these kinds of arrangements is in the pipeline? 

just wanted to confirm ... appreciate if anyone can provide insight on this!

**Comment by manoldonev** [comment]
@sis0k0 Can you share any details on adding support for router outlet animations in NativeScript/Angular?

**Comment by manoldonev** [comment]
@dgavigan btw, can you elaborate a bit on the scenario you are trying to achieve? (any context you can provide would be welcome). For example -- do you want to keep the tabs visible at all times while you have the master/detail implemented on a single tab, or maybe you would like the master list on tab, then detail screen to be opened on a separate page (no tabs interface visible), and upon back navigation to be returned on the starting master tab?

**Comment by sis0k0** [comment]
@dgavigan @manoldonev 
The support for routable animations on the `<router-outlet>` directive will be shipped either with the 4.2 or with the 4.3 release of nativescript-angular. So, in the best case - a week, and in the worst - 1-2 months.

**Comment by dgavigan** [comment]
@manoldonev sure thing! so the first scenario you described would be the ideal. 
* master detail within a tab view ... with tabs being accessible throughout the master detail navigation
* ability to navigate to further detail views from the original 
  -- Master --> Detail --> Detail

![tabs-master-detail](https://user-images.githubusercontent.com/2365581/28836433-7fd00d44-76ae-11e7-8a10-6d44f71c09e6.png)


@sis0k0 awesome! thanks for the heads up. This is what I originally thought, just wanted to confirm the solution lies within a future release. Thanks for all your efforts towards building {NS}!

**Comment by sis0k0** [comment]
@dgavigan just a follow-up on the router animations - they'll be part of the 4.2 release, which is coming in a few days.

**Comment by dgavigan** [comment]
thanks for the follow-up @sis0k0 ... super stoked!

**Comment by AhSem** [comment]
Hi, may I know if this tab-view template can already implement master-detail view within each tab view? 
If so, may I have sample source codes? 
Thank you

**Comment by thianlim** [comment]
+1
