### ISSUE TITLE
Use CSS, not SASS

### ISSUE THREAD

**Issue by tigerdi** [NativeScript/template-tab-navigation-ng#58]
Hi

I do not want to use SASS / SCSS, but just traditional CSS files. How can I change it? 

Thanks,

**Comment by NickIliev** [comment]
@tigerdi the template is structured to use SASS with [nativescript-theme-core](https://www.npmjs.com/package/nativescript-theme-core) plugin.
However, you can modify it to use CSS as the nativescript-theme-core plugin supports both plain CSS and SASS. This would require to change all files to CSS and make significant changes in the imported styles (removing the SASS variables and replacing them with proper CSS styles)7

Based on the README of the template here is the styling structure (file that needs to be changed)
Styling

> This template is set up to use SASS for styling. All classes used are based on the {N} core theme – consult the documentation to understand how to customize it. Check it out to see what classes you can use on which component.
> 
> It has 4 global style files that are located at the root of the app folder:
> 
> _app-variables.scss - holds the global SASS variables that are imported on each component's styles.
> app.scss - the global common style sheet. These style rules are applied to both Android and iOS.
> platform.android.scss - the global Android style sheet. These style rules are applied to Android only.
> platform.ios.scss - the global iOS style sheet. These style rules are applied to iOS only.
> Each component has 3 style files located in the its folder:
> 
> _component-name.component.scss - the component common style sheet. These style rules are applied to both Android and iOS.
> component-name.component.android.scss - the component Android style sheet. These style rules are applied to Android only.
> component-name.component.ios.scss - the component iOS style sheet. These style rules are applied to iOS only.
