### ISSUE TITLE
How do i add a new root component 

### ISSUE THREAD

**Issue by lastpeony** [NativeScript/template-tab-navigation-ng#59]
Hello im trying to add a new  root component which doesnt have tabs,just a page blank page or a page with a button.What i want to do is after pressing button on this page it should swiitch  tabs.

I couldnt really understand how routing works.Generated a login component like this:
https://image.prntscr.com/image/M-So__ruQz_tBNy61vM8SA.png
How do i set this login component as root component ? then how do i switch tabs component from this login component ?

**Comment by NickIliev** [comment]
@lastpeony this template has the initial routes  set [here](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/app-routing.module.ts#L6)
```JS
const routes: Routes = [
    { path: "", redirectTo: "/tabs", pathMatch: "full" },
    { path: "tabs", loadChildren: "./tabs/tabs.module#TabsModule" }
];
```

The above code basically says that for [AppModule](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/app.module.ts#L13) the default root will be `/tabs` and the `path` for `tabs` will use lazy loading to default to [TabsModule](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/tabs/tabs.module.ts). The `TabModule` routing table can be found [here](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/tabs/tabs-routing.module.ts#L7-L9) and will basically default to the single `TabsComponent` in this route table.

So to change the initial page (e.g. to the login screen) implement the route in the `app-routing.module.ts` and navigate to the wanted destination once the user has authenticated (e.g. `tabs` path.
From that point on we can use `clearHistory` and or route guards to verify that the user is logged / valid and he won't be able to navigate back (if the business logic requires this behavior).

More about routing in Angular can be found [here](https://angular.io/guide/router),.
This is [the documentation article about NativeScript specifics in Angular navigation](https://docs.nativescript.org/angular/core-concepts/angular-navigation#navigation).
And lastly you can see why we are recommending using lazy loading for your modules [here](https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading)
