### ISSUE TITLE
how do I create/add children routes inside of tabview items e.g. in Home.

### ISSUE THREAD

**Issue by g3gurung** [NativeScript/template-tab-navigation-ng#65]

**Comment by MartoYankov** [comment]
@g3gurung 
Currently, you can't use <page-router-outlet> inside a TabView item, but you can use the Angular <router-outlet>. Take a look at an example [here](https://docs.nativescript.org/angular/code-samples/routing). Note, that using the router-outlet and not page-router-outlet means you won't get the native animations and action bar by default.

We are currently working on the 4.0 release and we`re looking into making it possible to use the <page-router-outlet> inside a tab item.
