### ISSUE TITLE
Loading tabs are not proper when tabs are in the bottom

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/template-tab-navigation-ng#78]
Hi. 
There is a weird use case when the tabs are in the bottom. Imagine we have three tabs. When app is loaded, first and second tab get loaded, but when you go through the second tab, third tab don't get loaded.

As mentioned in the [blog post](https://www.nativescript.org/blog/guest-post-getting-cozy-with-nativescript's-tabview) : 

> One interesting thing about the TabView is how it handles (un)loading of each TabViewItem's view. When the TabView is first loaded, it loads up all of the items' views right then. However, as you navigate through the tabs, it starts unloading tabs that are more than one tab away from the presently selected tab, as well as loading any tabs that are only one tab away that have been unloaded

Also When tabs are in the bottom,  always unload tabs. (But when the tabs are in the top, it doesn't unload the nearest tab.) Is there any options to managing these loading and unloading views?

**Comment by MartoYankov** [comment]
@vahidvdn The TabView has undergone some major changes in the last releases which makes this blog post a bit obsolete. I suggest you take a look at the [docs article](https://docs.nativescript.org/angular/code-samples/ui/tab-view) for a detailed explanation on how it works now. I think you are looking for the `androidOffscreenTabLimit ` property.

**Comment by vahidvdn** [comment]
@MartoYankov Thanks. I am going to test the `androidOffscreenTabLimit` property. But that's related to loading the tab's item. Still it may starts unloading tabs that are more than one tab away from the presently selected tab. How can we manage unloading tabs for both android and iOS? (something like instagram)

**Comment by MartoYankov** [comment]
@vahidvdn This property should control both the loading and unloading. It's value specifies how many tabs to the sides of the current tab should be loaded. So if this value is set to 1, you should have 3 tabs loaded - the current one and one on each side. The default value for Android with top tabs is 1. The default value for Android with bottom tabs is 0 for compatibility reasons with iOS (also notice there is no swipe to navigate when bottom). On iOS there is no such native property and is effectively 0.

**Comment by vahidvdn** [comment]
@MartoYankov But some apps have that feature in iOS. For example iOS news app (that is installed by default in iOS) has that possibility. You can go through other tabs without unloading and when come back, you can see the previous scroll position.

**Comment by MartoYankov** [comment]
@vahidvdn Keeping the state is not connected to loading/unloading. We should be keeping the state in different tab items by default. In the template, you can scroll to bottom, go to second tab, return to first and the scroll position is kept. You can tap an item and navigate to detail, go to second tab, return to first and you should see the same detail page. Are you observing a different behavior?

**Comment by vahidvdn** [comment]
@MartoYankov Yes, that's not happening when `androidTabsPosition` is set to bottom. Before submitting the issue, I didn't know about `androidOffscreenTabLimit`. Now it works fine when position is top.

But when I set the position to the bottom, it completely ignore `androidTabsPosition`. It means when position is top, I scroll down in first tab (in a listView) then when I go through the second or third tab, I lost the scroll position in first tab (or it renders the first tab again).

Also in iOS you mentioned that there is no `androidTabsPosition` property at all. So the same problem may occur as I see in android when tabs are in bottom.
